### ISSUE TITLE
USB error 0: Unable to open USB device: Success

### ISSUE THREAD

**Issue by cl1ck** [git-moss/Push4Bitwig#185]
I get this error when running push2display on Windows 10 with JRE 1.8.0_66. The display stays blank.

**Comment by git-moss** [comment]
It's possible that the USB lookup does not yet cover all possibilities:
- Have you connected the device directly or through a USB hub? Try direct connection.
- Also try all other USB ports of your computer.

**Comment by adsn** [comment]
Hi,

I have the same error on xubuntu 15.10, regardless which USB port is used.
For testing I booted Windows 7 on the same machine and got the same error.

Fix for Windows 7:
I first tried to use Push2 directly after unboxing, so maybe this was the reason why it wasn't working properly. So after downloading Live Intro and following their guide, turning off USB suspending and letting Live update the Push firmware it was working properly.

Linux Problem however still persists, though I found a messy way around...

Running the display program with openjdk version "1.8.0_66-internal" gives following errors:

Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at push22bitwig.Push22Bitwig.main(Push22Bitwig.java:20)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

As workaround I use Bitwigs JRE, here the display app starts without errors but the USB device can't be found. Strangely by running the app as root the usb device is found and the display works.

I have to start Bitwig manually in this case otherwise the app would start Bitwig as root so my libs and license can't be found.


Anyway, thanks for providing push support!

**Comment by git-moss** [comment]
If I understand you correctly the fix was to update the Firmware, right?
Regarding Linux I am not sure if the Push 2 works on Linux at all. I need to set up a Linux machine for testing but dont have a spare machine currently. I could not make it work on a VM.

Regarding your start problem: OpenJDK does currently not support JavaFX. Therefore you need to use the Oracle JDK:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by adsn** [comment]
I had to disable USB powersave inside Device Manager first, then Live was able to update the firmware so I'm not sure if the update fixed this or preventing the device being send to sleep by windows...
My guess is it was the USB powersave (I'm using a laptop) which send the display directly to sleep, otherwise Live would have found it.

On Linux Push2 seems to work nicely, though I haven't tested very much yet.

Oracle JDK starts the app without errors, thanks for the tip, but the device is still only found when the app starts with root permissions.

**Comment by cl1ck** [comment]
I tried several USB ports (no hub) and updated the firmware, but unfortunately I still get this error. Do you have the source code for the Java application hosted somewhere on GitHub? Maybe I can help / fix it myself.

**Comment by git-moss** [comment]
@adsn I just released version 7. With that I tested all platforms and updated the installation documentation. It also includes how to run it without root.

@cl1ck I will publish the source in the next days.

**Comment by adsn** [comment]
Thanks, now everything works on Linux and the updates to the display are awesome!

**Comment by git-moss** [comment]
@cl1ck The source is now online if you want to take a look: https://github.com/git-moss/Push2Display
The USB lookup code is in USBDisplay.java

**Comment by git-moss** [comment]
@cl1ck I improved the USB lookup code. Please try again with the update I checked into this repository.

**Comment by cl1ck** [comment]
It's working perfectly now, thanks a lot! You're awesome

**Comment by destiriser** [comment]
I have the same error, the last Push 4 Bitwig version. This is in now way stable and I think it shouldn't be named as such. Can you fix this?

**Comment by git-moss** [comment]
Have you tried the latest version from GitHub?

**Comment by destiriser** [comment]
Yes.

**Comment by git-moss** [comment]
Do you get an error in the log window? Since you are on Linux: Have you added your user to a group which has access to the USB (see installation in the Wiki)?

**Comment by destiriser** [comment]
Yes, like this:
Starting UDP server on port 7000.
USB error 0: Unable to open USB device.: Success

I'm in audio group, the Push4Bitwig/push2display/99-userusbdevices.rules file was copied to /etc/udev/rules.d/

**Comment by git-moss** [comment]
From the errror message I think you are still running the old version. Make sure that the Push22Bitwig.jar is not anywhere else, one user had a copy in a folder of the Java VM (in the ext folder).

**Comment by destiriser** [comment]
I did a global search, didn't find anything with this name outside of the unpacked folder.

**Comment by git-moss** [comment]
I checked in a new version of Push2Display on GitHub which displays a version number in the title bar (also added to the JAR file). If this is displayed you can be sure it is the latest one.

**Comment by destiriser** [comment]
The version is 1.10.

**Comment by git-moss** [comment]
I checked the code again. It seems that the error handling for the device lookup was not correct. That's why the error message was so strange.
However it does not fix your problem. It should output now that the device simply can't be found.
I guess there is a specific problem on your system. I guess you already have tried different USB ports?
If you want to try digging deeper yourself: Here you can find some testcode, e.g. run the DumpDevices code which lists all the USB devices the library can find on the system.
https://github.com/usb4java/usb4java-examples/tree/master/src/main/java/org/usb4java/examples
