### ISSUE TITLE
Push 2 display app has heavy RAM consumption on Linux

### ISSUE THREAD

**Issue by adsn** [git-moss/Push4Bitwig#193]
After starting the app its RAM allocation slowly increases up to 2 Gig, then drops to 1 Gig and grows to 2 Gig again...
(see screenshot)

I have only 8 Gigs of Ram on my notebook so a quarter of memory is lost.
Is this normal behaviour or a bug?

![screen](https://cloud.githubusercontent.com/assets/7224346/12216151/020077aa-b6d9-11e5-85ef-56d602947e36.jpg)

**Comment by git-moss** [comment]
I see that behaviour on Windows too. From my analysis I think it is not an issue since if memory is needed the space gets cleaned up. You see that when you turn on the Preview, which cleans up the memory directly but with a higher hit on CPU. I experimented a bit with it and tried a workaround but that increased the CPU by 2% on my system. Therefore, I leave it as it is.
If you are worried about it you can turn on Preview but will loose the double of CPU.

**Comment by adsn** [comment]
Thanks for the explanation. The preview increases the CPU by 1% on my system so I can just leave preview on.
